import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const videoCourseIds = [
  "pet-food-safety",
  "pet-supplies",
  "pet-grooming-and-attachment",
  "puppy-habits",
  "lets-get-a-puppy-speaking",
  "pet-decision-and-care",
];

const englishCourseMetadata = Object.freeze({
  "pet-food-safety": {
    title: "Articles in Pet Food Safety",
    summary: "Practice a, an, and the through pet-food safety, including human foods that cats and dogs should not eat.",
  },
  "pet-supplies": {
    title: "Pet Supplies",
    summary: "Learn to ask about and describe common pet supplies, including collars, litter boxes, parrots, and cages.",
  },
  "pet-grooming-and-attachment": {
    title: "Pet Grooming & Attachment",
    summary: "Practice vocabulary for grooming, care, training, and the emotional bond with a new pet.",
  },
  "puppy-habits": {
    title: "Puppy Habits",
    summary: "Talk about a puppy's sleeping habits, daily care, and the love puppies give their owners.",
  },
  "lets-get-a-puppy-speaking": {
    title: "Let's Get a Puppy — Speaking",
    summary: "Practice a conversation about getting a puppy, including responsibility, training, and caring for a dog.",
  },
  "pet-decision-and-care": {
    title: "Getting a Pet: Decisions & Care",
    summary: "Ask for advice and discuss the practical decisions involved in caring for a pet.",
  },
});

const [courses, reviewItems] = await Promise.all([
  readFile(resolve(projectRoot, "state/courses.json"), "utf8").then(JSON.parse),
  readFile(resolve(projectRoot, "state/review-items.json"), "utf8").then(JSON.parse),
]);

const byCourseId = new Map(courses.map((course) => [course.id, course]));
const selectedCourses = videoCourseIds.map((courseId) => {
  const source = byCourseId.get(courseId);
  if (!source) throw new Error(`Missing video course: ${courseId}`);
  const english = englishCourseMetadata[courseId];
  return {
    id: source.id,
    title: english.title,
    summary_zh: english.summary,
    source_files: ["Video course"],
    card_ids: [...(source.card_ids || [])],
    order: source.order,
    selected_card_ids: [...(source.selected_card_ids || [])],
  };
});

const selectedCourseIds = new Set(videoCourseIds);
const selectedItems = reviewItems
  .filter((item) => selectedCourseIds.has(item.course_id))
  .map((item) => ({
    id: item.id,
    course_id: item.course_id,
    item: item.item,
    type: item.type || "sentence",
    source: "bundled video course",
    status: "new",
    last_result: "pending",
    next_due: "2025-01-01",
    interval_days: 1,
    example: item.example || item.item,
    note: "Translate the Chinese prompt into English. The reference answer is hidden by default.",
    prompt: item.prompt,
    accepted_answers: [...(item.accepted_answers || [])],
    history: [],
  }));

const itemKeys = new Set(selectedItems.map((item) => `${item.course_id}\u0000${item.id}`));
for (const course of selectedCourses) {
  if (course.card_ids.length !== new Set(course.card_ids).size) {
    throw new Error(`Duplicate card id in ${course.id}`);
  }
  if (course.card_ids.some((cardId) => !itemKeys.has(`${course.id}\u0000${cardId}`))) {
    throw new Error(`Course ${course.id} has a card without seed content`);
  }
  if (course.selected_card_ids.some((cardId) => !course.card_ids.includes(cardId))) {
    throw new Error(`Course ${course.id} selected content is not a full-content subset`);
  }
}

const seed = {
  courses: selectedCourses,
  review_items: selectedItems,
};

const output = `// Generated by tools/export_video_course_seed.mjs. Do not add learner progress here.\n(function initEnglishCoachVideoCourseSeed(root, factory) {\n  const api = factory();\n  if (typeof module === "object" && module.exports) module.exports = api;\n  root.EnglishCoachVideoCourseSeed = api;\n})(typeof globalThis !== "undefined" ? globalThis : this, function buildVideoCourseSeed() {\n  const seed = Object.freeze(${JSON.stringify(seed, null, 2)});\n\n  function workspace() {\n    return JSON.parse(JSON.stringify(seed));\n  }\n\n  return { workspace };\n});\n`;

await writeFile(resolve(projectRoot, "web/assets/video-course-seed.js"), output, "utf8");
console.log(`Exported ${selectedCourses.length} courses and ${selectedItems.length} cards.`);
